{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.job_db_init }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.db_init }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipyard-db-init
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "shipyard" "db-init" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      initContainers:
{{ tuple $envAll $dependencies "[]" | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: shipyard-db-init
          image: {{ .Values.images.db_init | quote }}
          imagePullPolicy: {{ .Values.images.pull_policy | quote }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.db_init | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
            - name: ROOT_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.oslo_db.admin }}
                  key: DB_CONNECTION
            - name: DB_NAME
              value: shipyard
            - name: DB_USER
              value: {{ .Values.endpoints.oslo_db.auth.user.username }}
            - name: DB_PASS
              value: {{ .Values.endpoints.oslo_db.auth.user.password }}
            - name: DB_PORT
              value: '5432'
            - name: DB_FQDN
              value: {{ .Values.endpoints.oslo_db.hosts.default }}
            - name: ROOT_DB_USER
              value: postgres
          command:
            - /tmp/db-init.sh
          volumeMounts:
            - name: shipyard-bin
              mountPath: /tmp/db-init.sh
              subPath: db-init.sh
              readOnly: true
      volumes:
        - name: shipyard-bin
          configMap:
            name: shipyard-bin
            defaultMode: 0555
{{- end }}
