# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.ks_endpoints }}

apiVersion: batch/v1
kind: Job
metadata:
  name: drydock-ks-endpoints
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      initContainers:
{{ tuple $envAll $dependencies "[]" | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
{{- range $key1, $osServiceType := tuple "physicalprovisioner" }}
{{- range $key2, $osServiceEndPoint := tuple "admin" "internal" "public" }}
        - name: {{ $osServiceType }}-ks-endpoints-{{ $osServiceEndPoint }}
          image: {{ $envAll.Values.images.ks_endpoints }}
          imagePullPolicy: {{ $envAll.Values.images.pull_policy }}
          {{- if $envAll.Values.resources.enabled }}
          resources:
            requests:
              memory: {{ $envAll.Values.resources.ks_endpoints.requests.memory | quote }}
              cpu: {{ $envAll.Values.resources.ks_endpoints.requests.cpu | quote }}
            limits:
              memory: {{ $envAll.Values.resources.ks_endpoints.limits.memory | quote }}
              cpu: {{ $envAll.Values.resources.ks_endpoints.limits.cpu | quote }}
          {{- end }}
          command:
            - /tmp/ks-endpoints.sh
          volumeMounts:
            - name: ks-endpoints-sh
              mountPath: /tmp/ks-endpoints.sh
              subPath: ks-endpoints.sh
              readOnly: true
          env:
{{- with $env := dict "ksUserSecret" $envAll.Values.secrets.identity.admin }}
{{- include "helm-toolkit.snippets.keystone_openrc_env_vars" $env | indent 12 }}
{{- end }}
            - name: OS_SVC_ENDPOINT
              value: {{ $osServiceEndPoint }}
            - name: OS_SERVICE_NAME
              value: {{ tuple $osServiceType $envAll | include "helm-toolkit.endpoints.keystone_endpoint_name_lookup" }}
            - name: OS_SERVICE_TYPE
              value: {{ $osServiceType }}
            - name: OS_SERVICE_ENDPOINT
              value: {{ tuple $osServiceType $osServiceEndPoint "api" $envAll | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" }}
{{- end }}
{{- end }}
      volumes:
        - name: ks-endpoints-sh
          configMap:
            name: drydock-bin
            defaultMode: 0555
