# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file provides defaults for shipyard

replicas:
  shipyard: 1

images:
  shipyard: docker.io/eanylin/shipyard:v0.2.0
  dep_check: docker.io/kolla/ubuntu-source-kubernetes-entrypoint:4.0.0
  pull_policy: "IfNotPresent"

network:
  shipyard:
    name: shipyard-api
    port: 9000
    node_port:
      enabled: true
      port: 31901

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

conf:
  shipyard:
    override:
    append:
    default:
      base:
        web_server: http://web.shipyard:8080

resources:
  enabled: false
  shipyard:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "128Mi"
      cpu: "100m"

