{{ include "airflow.cfg.airflow_values_skeleton" .Values.conf.airflow | trunc 0 }}

{{- if empty .Values.conf.airflow.default.core.sql_alchemy_conn -}}
{{ tuple "postgresql" "internal" "user" "postgresql" . | include "helper.authenticated_endpoint_uri_lookup" | set .Values.conf.airflow.default.core "sql_alchemy_conn" | quote | trunc 0 -}}
{{- end }}

{{- if empty .Values.conf.airflow.default.celery.broker_url -}}
{{ tuple "messaging" "internal" "user" "amqp" . | include "helper.authenticated_endpoint_uri_lookup" | set .Values.conf.airflow.default.celery "broker_url" | quote | trunc 0 -}}
{{- end }}

{{- if empty .Values.conf.airflow.default.celery.celery_result_backend -}}
{{ tuple "messaging" "internal" "user" "amqp" . | include "helper.authenticated_endpoint_uri_lookup" | set .Values.conf.airflow.default.celery "celery_result_backend" | quote | trunc 0 -}}
{{- end }}


apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-etc
data:
  airflow.cfg: |+
{{ if .Values.conf.airflow.override -}}
{{ .Values.conf.airflow.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.airflow.prefix -}}
{{ .Values.conf.airflow.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_airflow.cfg.tpl" . | include "helper.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.airflow.append -}}
{{ .Values.conf.airflow.append | indent 4 }}
{{- end }}
