apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-bin
data:
  db-init.sh: |+
{{ tuple "bin/_db-init.sh.tpl" . | include "helper.template" | indent 4 }}
  db-sync.sh: |+
{{ tuple "bin/_db-sync.sh.tpl" . | include "helper.template" | indent 4 }}
