# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.manifests.deployment_web }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.server }}
{{- $mounts_airflow_web := .Values.pod.mounts.airflow_web.airflow_web }}
{{- $mounts_airflow_web_init := .Values.pod.mounts.airflow_web.init_container }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: airflow-web
spec:
  replicas: {{ .Values.pod.replicas.airflow.web }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "airflow" "web" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.pod.lifecycle.termination_grace_period.server.timeout | default "30" }}
      initContainers:
{{ tuple $envAll $dependencies $mounts_airflow_web_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: airflow-web
          image: {{ .Values.images.airflow }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.airflow.web | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
          - name: AIRFLOW_CONN_AIRFLOWS_OWN_DB
            valueFrom:
                secretKeyRef:
                    name: {{ .Values.secrets.postgresql.admin }}
                    key: DB_CONNECTION
          ports:
            - containerPort: {{ .Values.network.airflow.web.port }}
          args: ["webserver"]
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.airflow.web.port }}
          volumeMounts:
            - name: airflow-etc
              mountPath: /usr/local/airflow/airflow.cfg
              subPath: airflow.cfg
              readOnly: true
            - name: dags
              mountPath: /usr/local/airflow/dags
            - name: plugins
              mountPath: /usr/local/airflow/plugins
            - name: logs
              mountPath: /usr/local/airflow/logs
{{ if $mounts_airflow_web.volumeMounts }}{{ toYaml $mounts_airflow_web.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: airflow-etc
          configMap:
            name: airflow-etc
            defaultMode: 0444
        - name: dags
          hostPath:
            path: {{ .Values.pod.mounts.dag_path }}
        - name: plugins
          hostPath:
            path: {{ .Values.pod.mounts.plugin_path }}
        - name: logs
          hostPath:
            path: {{ .Values.pod.mounts.log_path }}
{{ if $mounts_airflow_web.volumes }}{{ toYaml $mounts_airflow_web.volumes | indent 8 }}{{ end }}
{{- end }}
