{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.server }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.replicas.worker }}
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helper.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      restartPolicy: Always
      containers:
      - name: worker
        image: {{ .Values.images.airflow }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        {{- if .Values.resources.enabled }}
        resources:
          requests:
            memory: {{ .Values.resources.worker.requests.memory | quote }}
            cpu: {{ .Values.resources.worker.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.worker.limits.memory | quote }}
            cpu: {{ .Values.resources.worker.limits.cpu | quote }}
        {{- end }}
        volumeMounts:
          - name: dags
            mountPath: /usr/local/airflow/dags
          - name: docker
            mountPath: /var/run
            readOnly: false
          - name: pod-var-lib-docker
            mountPath: /var/lib/docker
            readOnly: false
        args: ["worker"]
        ports:
        - name: worker
          containerPort: 8793
        securityContext:
          privileged: true
      volumes:
      - name: dags
        hostPath:
          path: {{ .Values.volumes.path }}
      - name: docker
        hostPath:
          path: /var/run
      - name: pod-var-lib-docker
        hostPath:
          path: /var/lib/docker

