apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: {{ .Values.replicas.flower }}
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
    spec:
      restartPolicy: Always
      containers:
      - name: flower
        image: {{ .Values.images.airflow }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        ports:
        - name: flower
          containerPort: 5555
        args: ["flower"]
