apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: {{ .Values.replicas.flower }}
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
    spec:
      restartPolicy: Always
      containers:
      - name: flower
        image: {{ .Values.images.airflow }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        {{- if .Values.resources.enabled }}
        resources:
          requests:
            memory: {{ .Values.resources.flower.requests.memory | quote }}
            cpu: {{ .Values.resources.flower.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.flower.limits.memory | quote }}
            cpu: {{ .Values.resources.flower.limits.cpu | quote }}
        {{- end }}
        ports:
        - name: flower
          containerPort: 5555
        args: ["flower"]
