{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.init }}
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init-postgresql
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies "[]" | include "helper.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: airflow-db-init-postgresql
          image: {{ .Values.images.db_init_postgresql | quote }}
          imagePullPolicy: {{ .Values.images.pull_policy | quote }}
          env:
            - name: DB_NAME
              value: airflow
            - name: DB_USER
              value: {{ .Values.endpoints.postgresql.auth.user.username }}
            - name: DB_PASS
              value: {{ .Values.endpoints.postgresql.auth.user.password }}
            - name: DB_PORT
              value: '5432'
            - name: DB_FQDN
              value: {{ .Values.endpoints.postgresql.hosts.default }}
            - name: ROOT_DB_USER
              value: postgres
          command:
            - bash
            - /tmp/db-init.sh
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.jobs.db_sync.limits.cpu | quote }}
              memory: {{ .Values.resources.jobs.db_sync.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.jobs.db_sync.requests.cpu | quote }}
              memory: {{ .Values.resources.jobs.db_sync.requests.memory | quote }}
          {{- end }}
          volumeMounts:
            - name: airflow-etc
              mountPath: /usr/local/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: airflow-bin
              mountPath: /tmp/db-init.sh
              subPath: db-init.sh
              readOnly: true
      volumes:
        - name: airflow-etc
          configMap:
            name: airflow-etc
        - name: airflow-bin
          configMap:
            name: airflow-bin
