apiVersion: v1
kind: Secret
metadata:
  name: airflow-db-root
type: Opaque
data:
  DB_CONNECTION_POSTGRESQL: {{ tuple "postgresql" "internal" "admin" "postgresql" . | include "helper.authenticated_endpoint_uri_lookup" | b64enc }}

