apiVersion: v1
kind: Service
metadata:
  name: flower
spec:
  {{ if .Values.network.flower.enable_node_port }}
  type: NodePort
  {{ end }}
  selector:
    app: airflow
    tier: flower
  ports:
    - name: flower
    {{ if .Values.network.flower.enable_node_port }}
      nodePort: {{ .Values.network.flower.node_port }}
    {{ end }}
      port: {{ .Values.network.flower.port }}
      protocol: TCP
      targetPort: flower
