apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: airflow
    tier: web
  ports:
    - name: web
    {{ if .Values.network.web.enable_node_port }}
      nodePort: {{ .Values.network.web.node_port }}
      port: {{ .Values.network.web.port }}
      protocol: TCP
      targetPort: web
    {{ else }}
      port: {{ .Values.network.web.port }}
      protocol: TCP
      targetPort: web
    {{ end }}
