apiVersion: v1
kind: Service
metadata:
  name: flower
spec:
  selector:
    app: airflow
    tier: flower
  ports:
    - name: flower
    {{ if .Values.network.flower.node_port.enabled }}
      nodePort: {{ .Values.network.flower.node_port.port }}
    {{ end }}
      port: {{ .Values.network.flower.port }}
      protocol: TCP
      targetPort: flower
  {{ if .Values.network.flower.node_port.enabled }}
  type: NodePort
  {{ end }}
